apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-web-app
spec:
  ingressClassName: nginx 
  rules:
  - host: afc190e570afd494ea317ca970b58ee8-094d19001f2f0cd4.elb.us-east-1.amazonaws.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: go-web-app
            port:
              number: 80
 
